### ISSUE TITLE
Host example app on gh-pages

### ISSUE THREAD

**Issue by patrickarlt** [Esri/geotrigger-faker#46]
So we can direct people there instead of hosting the app on the developers site.

**Comment by ungoldman** [comment]
https://github.com/Esri/geotrigger-faker/tree/master/examples/browser should be more or less ready to deploy to `gh-pages`

hi pat 👋

**Comment by jgravois** [comment]
[confirmed](http://esri.github.io/geotrigger-faker/examples/browser/).

**Comment by jgravois** [comment]
given the looming 🌆  of the geotrigger service, i have deleted the `gh-pages` branch of the faker.
